POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "test",
    "number": "111-11324"
}

### 
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "number": "test number 0123"
}

###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Arto Hellas",
    "number": "1234556"
}

### Send to online app
POST https://fullstackopen-part3-cxfh.onrender.com/api/persons
content-type: application/json

{
    "name": "test",
    "number": "test number 0123"
}
